version: 0.0
os: linux
files:
  - source: ./
    destination: /opt/frontend/dad_management/
hooks:
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 250
      runas: root
  ApplicationStart:
    - location: codedeploy/application_start.sh
      timeout: 250
      runas: root
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 250
      runas: root
